### ISSUE TITLE
Why demo docs otelcol-config.yml file and runtime config files are different?

### ISSUE THREAD

**Issue by EmrhT** [open-telemetry/opentelemetry-demo#1324]
# Question

hello, I installed the demo env with helm charr. within demo docs and repository, otel collector config file is given as https://github.com/open-telemetry/opentelemetry-demo/blob/main/src/otelcollector/otelcol-config.yml. 

However, when I deep dived to explore my-otel-demo-otelcol-xxx container runtime, I discovered two different config files both of which are different that the one given above. First one is /conf/relay.yaml, second is /etc/otelcol-contrib/config.yaml. 

Entrypoint process of the container is using the first config file as it can be seen below. 
![image](https://github.com/open-telemetry/opentelemetry-demo/assets/33878173/279a8b9d-fb95-4b17-9fa1-13adfc3be8a7)

It is given to the runtime via mounting my-otel-demo-otelcol configmap as a volume in deployment.

Can you explain why those files are different and if there is a relation between those that I'm missing (like auto-generation from each other)?

Thanks in advance.

**Comment by puckpuck** [comment]
The Demo's Helm chart depends upon the OpenTelemetry Collector chart. The Collector chart is what sets the usage of `/conf/relay.yaml` for the config file. The chart also specifies several default configuration options that are not modified for the Demo, which will contribute to the contents not matching what is in the Demo's repo. This is intentional, as we want the Kubernetes deployment to take advantage of what is offered in that world, while keeping what is in the repo itself to just what is required for a local deployment.
