### ISSUE TITLE
Feature Flag not considering `defaultVariant`

### ISSUE THREAD

**Issue by julianocosta89** [open-telemetry/opentelemetry-demo#1492]
# Bug Report

When starting the demo as is, without any code changes, the `adServiceFailure` feature flag is like this:

```json
    "adServiceFailure": {
      "description": "Fail ad service",
      "state": "ENABLED",
      "variants": {
        "on": true,
        "off": false
      },
      "defaultVariant": "off",
      "targeting": {
        "fractional": [
          {
            "var": "session"
          },
          [
            "on",
            10
          ],
          [
            "off",
            90
          ]
        ]
      }
    },
```

According to our docs, the Feature Flag should only be active if `defaultVariant` is set to `on`, but in this case this is not working.

The 10% on the fractional is being used even though the `defaultVariant` is `off`.

Is this an issue in our docs, or with `flagd`?

Tagging @austinlparker and @beeme1mr for visibility.

**Comment by beeme1mr** [comment]
Hey @julianocosta89, can you confirm that the evaluation context property named `session` is used during the flag evaluation? It's also important that this property isn't hardcoded because of how the bucketing algorithm works. You can read more about it [here](https://flagd.dev/reference/custom-operations/fractional-operation/). My guess is that the value is either not being passed correctly or it's a static hardcoded value.

We don't support truly random traffic splitting because typically you don't want random behavior between requests for the same user (or session). In this case, since you may actually want random requests to fail, you could do something like this.

```json
    "adServiceFailure": {
      "description": "Fail ad service",
      "state": "ENABLED",
      "variants": {
        "on": true,
        "off": false
      },
      "defaultVariant": "off",
      "targeting": {
        "fractional": [
          {
            "var": "$flagd.timestamp"
          },
          [
            "on",
            10
          ],
          [
            "off",
            90
          ]
        ]
      }
    },
```

This is a bit of a hack but may work well in this situation. It uses the current timestamp as the bucketing identifier. The `$flagd.timestamp` is added to the evaluation context [automatically](https://flagd.dev/reference/flag-definitions/#flagd-properties-in-the-evaluation-context).

**Comment by beeme1mr** [comment]
The default variant is only used when there's no match in the targeting rule. In this case, you could update the rule to return `null` 90% of the time. It would then fall back to the default variant.

**Comment by julianocosta89** [comment]
Got it!
Thank you @beeme1mr!
