### ISSUE TITLE
Install OpenTelemetry applications (excluding observability stack)

### ISSUE THREAD

**Issue by tranngoclam** [open-telemetry/opentelemetry-demo#1508]
# Feature Request

**Is your feature request related to a problem?**

- Currently the opentelemetry-demo compose file/helm chart contains all applications (frontend, adservice, accountingservice, ...) and observability stack (otel-collector, grafana, prometheus, ...), which is not possible to reuse the applications in other places.
- In details, I am building my own repository which contains my observability stack (otel-collector, grafana, loki, prometheus, tempo, or even saas-based stack), and I want to have the demo apps running along with my observability stack without copying the whole implementation (source code + manifest files)

**Describe the solution you'd like:**

- With docker compose, it has an experimental feature **include** with remote importing by a path (reference: https://www.docker.com/blog/scaling-docker-compose-up)
- If we make the demo apps reusable in a separate compose file (demo-compose.yaml) which contains only demo apps, no observability stack, we can import it as:

**my-compose.yaml**

```
- include: git@github.com:open-telemetry/opentelemetry-demo.git
  path: demo-compose.yaml
```

**Describe alternatives you've considered.**

N/A

## Additional Context

N/A

**Comment by puckpuck** [comment]
Using Helm, this is possible. You can set the `enabled: false` property for each of the observability components, which will disable them from being included.

For Docker Compose, last year, we explored multiple different ways to run the demo. We did this because we received feedback that the demo with Kafka and some other components was becoming too large. This is where the docker-compose.minimal.yml file comes from. While doing this, we also explored making the observability and other demo components optional, but we decided not to because of user complexity.

**Comment by puckpuck** [comment]
@tranngoclam does the ability to disable the default observability components in the Helm chart satisfy your needs?

**Comment by tranngoclam** [comment]
> @tranngoclam does the ability to disable the default observability components in the Helm chart satisfy your needs?

yes @puckpuck, for helm chart it satisfy my requirement, let me use it and close this issue
