### ISSUE TITLE
[currencyservice] - docker build takes more than 15 minutes

### ISSUE THREAD

**Issue by puckpuck** [open-telemetry/opentelemetry-demo#252]
Running `docker compose build` takes more than 15 minutes just for the currency service using a 2019 MacBook Pro. Docker resources are set to 8 CPUs and 8 GB of RAM. The build time seems to be on the excessive side. 

Can we find a way to significantly reduce the build times for this service which is created in C++?

To replicate: build with the `--no-cache` option and observe the currencyservice build time in the console output
```
docker compose build --no-cache
```

**Comment by wph95** [comment]
Incidentally, I don't see very long build times on the github action (probably because of the high number of machine cpu/mem)
https://github.com/open-telemetry/opentelemetry-demo/runs/7221028577

// We plan to update the documentation this week. This will include how to use pre-built docker images so that you can use them without local builds

**Comment by cartersocha** [comment]
FYI @lalitb , @DebajitDas

**Comment by lalitb** [comment]
gRPC builds take time, and would take ~70% of currency-service build time. We can have the prebuilt gRPC library stored somewhere in cloud/registry and use it for currency-service docker build. But better to provide pre-built docker image for currency-service and as I understand, it is already planned.
