### ISSUE TITLE
Strange adservice behavior. Is it intentional?

### ISSUE THREAD

**Issue by madhead** [open-telemetry/opentelemetry-demo#586]
# Bug Report

Version: `v1.1.0` / `9a66c3a7e490dc0a30c738b92d931d04ce42f479` / `main` (just plain `git clone`)

## Symptom

It seems that the request for the ad is crafted incorrectly. It results in random ads being served.

After a quick looking at the docs and scenarios it's not clear whether it's intentional or not.

**What is the expected behavior?**

Appropriate adds are served for every request.

**What is the actual behavior?**

Random ad is served for every request.

## Reproduce

1. Open any product page. E.g. "Optical Tube Assembly": http://localhost:8080/product/9SIQT8TOJO. This `9SIQT8TOJO` is a product id, right?
2. A request is seen in browser's developers console: http://localhost:8080/api/data?productIds=9SIQT8TOJO
3. This `9SIQT8TOJO` is used to query `adservice`: https://github.com/open-telemetry/opentelemetry-demo/blob/9a66c3a7e490dc0a30c738b92d931d04ce42f479/src/frontend/pages/api/data.ts#L12
4. A request arrives in `adservice`:
    ```
    ad-service               | 2022-11-15 20:57:22 - hipstershop.AdService - received ad request (context_words=[9, S, I, Q, T, 8, T, O, J, O]) trace_id=e8c29c9773b16a424d5383acb41a2f15 span_id=ecd925196c0ed6c9 trace_flags=01
    ```
    ![image](https://user-images.githubusercontent.com/577360/202024417-85ca57eb-1bb5-43a4-bf62-7c7e816988e2.png)
5. So this `9SIQT8TOJO` is treated as ten separate context words.
6. The ads map doesn't contain any ads for any of these letters: https://github.com/open-telemetry/opentelemetry-demo/blob/9a66c3a7e490dc0a30c738b92d931d04ce42f479/src/adservice/src/main/java/hipstershop/AdService.java#L221-L227
7. Thus, no ads found and the ads request falls back to the `getRandomAds` any time.
8. This is also seen in Jaeger (all the requests have a call to the `getRandomAds` at the end):
    ![image](https://user-images.githubusercontent.com/577360/202025334-7a7ea8e1-e79c-478e-9554-b5042cb19d87.png)

## Additional Context

N/A

**Comment by breedx-splk** [comment]
Yeah, the adservice API is only designed to receive product categories, not IDs. I think the invoker should be passing product categories instead of ids.

The complexity of the client-side stack is a little beyond me, but [this line](https://github.com/open-telemetry/opentelemetry-demo/blob/9a66c3a7e490dc0a30c738b92d931d04ce42f479/src/frontend/gateways/rpc/Ad.gateway.ts#L9) is suspect, as is this [Ad.provider](https://github.com/open-telemetry/opentelemetry-demo/blob/32d1ee681042e55cb2c360d918a4928de50325c2/src/frontend/providers/Ad.provider.tsx#L24) which seems founded on product IDs.

In turn, that provider is used in 3 pages:  [cart](https://github.com/open-telemetry/opentelemetry-demo/blob/98f8bf54eb0a6a5c2c6adc1cb46b870d2c5eb196/src/frontend/pages/cart/index.tsx#L17), [order](https://github.com/open-telemetry/opentelemetry-demo/blob/d1687904f052e3694ab21a2dcda35ed151b5c4e7/src/frontend/pages/cart/checkout/%5BorderId%5D/index.tsx#L19), and [product](https://github.com/open-telemetry/opentelemetry-demo/blob/32d1ee681042e55cb2c360d918a4928de50325c2/src/frontend/pages/product/%5BproductId%5D/index.tsx#L51).

I cant follow the types enough to know how much work it would be to pass categories. Products definitely have categories as a list of strings, but I can't tell how `item` or `query` relate to products here.

**Comment by madhead** [comment]
@breedx-splk, correct. If you agree that current behavior is a bug, please, check out the linked PR.
