### ISSUE TITLE
Review and enhance metric support for ad service service (Java)

### ISSUE THREAD

**Issue by cartersocha** [open-telemetry/opentelemetry-demo#73]
The following are requirements for metrics in the project. Not all services will meet all requirements.

- [ ] Service metrics should not be duplicative of trace-derived metrics.
- [ ] Services should emit multiple business metrics where appropriate.
- [ ] Services should emit trace exemplars for their metrics.
- [ ] Services should use push metrics where possible.
- [ ] Services should explicitly read baggage where needed.
- [ ] Collectors should perform metric transforms to normalize resource and service metrics.

Referencing issue: https://github.com/open-telemetry/opentelemetry-demo-webstore/issues/43

**Comment by jlawrienyt** [comment]
Proposed Solution:

The Ad Service already has some business logic around whether to [deliver targeted ads or random ads, based on the context and ad availability](https://github.com/open-telemetry/opentelemetry-demo/blob/main/src/adservice/src/main/java/hipstershop/AdService.java#L116).  We should capture this decision as a single metric named `app.ads.ad_requests` with two dimensions: `ad_request_type` with possible values `TARGETED` and `NOT_TARGETED`; and `ad_response_type` with possible values `TARGETED` and `RANDOM`.

Currently, the code path that would serve a random ad is not being exercised by the load generator, nor is it possible to exercise it by browsing the demo site, because [all products](https://github.com/open-telemetry/opentelemetry-demo/blob/main/src/productcatalogservice/products.json) have categories with [associated ads](https://github.com/open-telemetry/opentelemetry-demo/blob/main/src/adservice/src/main/java/hipstershop/AdService.java#L188).  I propose we add a new product in a new category that does have an associated ad in order to demonstrate this behavior.  We should probably do this regardless of the metrics change as the [`getRandomAds` span](https://github.com/open-telemetry/opentelemetry-demo/blob/main/src/adservice/src/main/java/hipstershop/AdService.java#L159) is not currently getting produced.

cc @puckpuck

**Comment by austinlparker** [comment]
Closing as basic metrics have been added
