### ISSUE TITLE
Dependencies for update cadence

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry-demo#831]
The following are the containers/services we have dependencies on and versions as of 1.4 -

postgres - latest from 14.x (currently upto 15.x)
kafka - latest (ubi8)
redis - latest (alpine)
jaeger - latest
grafana - fixed to 9.2.15 (latest is: 9.4.7)
prometheus - fixed to 2.43.0 (current)
otel collector - fixed to 0.75.0 (current)

We should be updating/testing these updates on a fixed cadence.

**Comment by puckpuck** [comment]
All dependencies not use a fixed minor or patch version instead of just latest

As part of prepping for a new release, there should be a check to ensure all dependencies are current. Do we need to document this as part of our Making a new release [docs](https://github.com/open-telemetry/opentelemetry-demo/blob/main/CONTRIBUTING.md#making-a-new-release)?

**Comment by austinlparker** [comment]
Closing this as part of issue cleanup. If there's anything that needs to be done, please create a new issue.
